name: build-deploy
run-name: Build, Deploy to UAT and Test - from user @${{ github.actor }}

on: 
  workflow_dispatch:
    inputs:
      sut:
        description: 'Testsystem IP address'
        required: true

env:
  UAT_IP: ${{ inputs.sut }}
  UAT_TOMCAT: /home/ec2-user/tomcat/apache-tomcat-9.0.71/webapps
  UAT_PORT: 22

jobs:
  check_env: 
    runs-on: ubuntu-latest
    environment: UAT
    
    steps: 
     - name: print IP address
       run: echo "${{ env.UAT_IP }}"
       
     - name: lookup if $UAT_IP is accessible
       uses: appleboy/ssh-action@master
       with:
         host: ${{ env.UAT_IP }}
         username: ${{ secrets.USER }}
         key: ${{ secrets.SSH_KEY }}
         port: ${{ env.UAT_PORT }}
    
  build_and_test_and_deploy:
    needs: [check_env]
    environment: UAT
    name: Build and run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Run Unit Tests
        run: mvn test

      - name: Build with Maven
        run: mvn -DskipTests -B package --no-transfer-progress --file ./pom.xml

      - name: rename Artefakt
        run: mv ./target/*digitalbank*.war ./target/digibank.war

      - uses: actions/upload-artifact@master
        with:
          name: digibank.war
          path: ./target/digibank*
      
      - name: cleanup destination at $UAT_IP
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.UAT_IP }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ env.UAT_PORT }}
          script: rm -rf ./deployment/*

      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ env.UAT_IP }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ env.UAT_PORT }}
          source: './target/digibank.war'
          target: 'deployment'

    ### Install STEP ###
  install:
    needs: [build_and_test_and_deploy]
    environment: UAT
    name: Install Application
    runs-on: ubuntu-latest

    steps:
      - name: deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.UAT_IP }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ env.UAT_PORT }}
          script: cp -f /home/ec2-user/deployment/target/digibank.war ${{ env.UAT_TOMCAT }}

  e2e_tests:
     needs: [install]
     name: "Run end-2-end tests for the ip ${{ env.UAT_IP }}"
     runs-on: ubuntu-latest
        
     steps:
      - uses: actions/checkout@v3
      
      - name: Check IP 
        run: echo "${{ env.UAT_IP }}"

      - uses: actions/setup-node@v3
        with:
          host: ${{ env.UAT_IP }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ env.UAT_PORT }}
          node-version: 20
          cache: 'npm'

      - name: Install dependencies and run tests
        run: npm install

      - name: Install Playwright Dependencies
        run: npx playwright install

      - name: run the tests
        run: SUT="http://${{ env.UAT_IP }}:8080/digibank/login" npx playwright test
             
      - if: always()
        uses: actions/upload-artifact@master
        with:
          name: test-report.html
          path: ./playwright-report/index.html