name: Java CI with Gradle

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Build with Gradle
      run: ./gradlew clean build

    - name: Run tests with Gradle
      run: ./gradlew test

    - name: Generate code coverage report
      run: ./gradlew jacocoTestReport

    - name: Ensure code coverage is above 80%
      run: |
        COVERAGE=$(grep -oP 'Total.*?\K\d+(?=%)' build/reports/jacoco/test/html/index.html | head -1)
        echo "Code coverage is $COVERAGE%"
        if [ "$COVERAGE" -lt 80 ]; then
          echo "Code coverage is below 80% ($COVERAGE%). Failing the build."
          exit 1
        else
          echo "Code coverage is sufficient ($COVERAGE%)."
        fi

    - name: Clean up
      run: ./gradlew clean