name: Build and Run e2e tests
run-name: Deploy to ${{ github.event.client_payload.sut }} trigger via >${{ github.event_name }}< by @${{ github.actor }}

on:
  push:
    branches: [ "main" ]

jobs:
  e2e-tests:
    name: "Run end-2-end tests for the ip ${{ github.event.client_payload.sut }}"
    runs-on: ubuntu-latest
        
    steps:
      - uses: actions/checkout@v3
        
      - name: Check IP
        run: echo "${{ github.event.client_payload.sut }}"

      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies and run tests
        run: npm install

      - name: Install Playwright Dependencies
        run: npx playwright install

      - name: run the tests
        run: SUT="http://${{ github.event.client_payload.sut }}:8080/digibank/login" npx playwright test
             
      - if: always()
        uses: actions/upload-artifact@master
        with:
          name: test-report.html
          path: ./playwright-report/index.html